//! Auto-generated C bindings from `capi.h`.
//!
//! This file is generated by `bindgen` during the build process (`build.rs`).
//! DO NOT edit manually. Any changes will be overwritten on the next build.
//!
//! To inspect what bindgen produced, run:
//!   find target/ -name "bindings.rs" -exec cat {} \;

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
